# Generated by Django 5.1.4 on 2025-07-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_diet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionintake',
            name='location',
        ),
    ]
