# Generated by Django 5.1.4 on 2025-07-05 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_diet', '0001_initial'),
        ('emr', '0029_encounter_discharge_summary_advice'),
        ('facility', '0477_alter_facility_facility_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('quantity', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('allergens', models.JSONField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('entered-in-error', 'Entered In Error')], max_length=32)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed'), ('not-done', 'Not Done'), ('entered-in-error', 'Entered In Error'), ('unknown', 'Unknown')], max_length=32)),
                ('status_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('intake_items', models.JSONField()),
                ('occurrence_datetime', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.encounter')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facility.facility')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('on-hold', 'On Hold'), ('revoked', 'Revoked'), ('completed', 'Completed'), ('entered-in-error', 'Entered In Error'), ('unknown', 'Unknown')], max_length=32)),
                ('schedule', models.JSONField()),
                ('note', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facility.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
