# Generated by Django 5.1.4 on 2025-08-20 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_diet', '0002_remove_nutritionintake_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionintake',
            name='nutrition_order',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='intake_logs', to='care_diet.nutritionorder'),
            preserve_default=False,
        ),
    ]
