# Generated by Django 5.1.4 on 2025-07-23 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_diet', '0002_nutritionproduct_nutritionintake_nutritionorder'),
        ('emr', '0030_encounter_tags_medicationrequest_dispense_status_and_more'),
        ('facility', '0478_facility_discount_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
        migrations.AddField(
            model_name='nutritionintake',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='emr.facilitylocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionintake',
            name='service_type',
            field=models.CharField(choices=[('food', 'Food')], default='food', max_length=32),
        ),
        migrations.AddField(
            model_name='nutritionorder',
            name='encounter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='emr.encounter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionorder',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='emr.facilitylocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionorder',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='care_diet.nutritionproduct'),
        ),
        migrations.AddField(
            model_name='nutritionorder',
            name='service_type',
            field=models.CharField(choices=[('food', 'Food')], default='food', max_length=32),
        ),
        migrations.AddField(
            model_name='nutritionproduct',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='facility.facility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionproduct',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='emr.facilitylocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionproduct',
            name='service_type',
            field=models.CharField(choices=[('food', 'Food')], default='food', max_length=32),
        ),
        migrations.AlterField(
            model_name='nutritionintake',
            name='status',
            field=models.CharField(choices=[('preparation', 'Preparation'), ('in-progress', 'In Progress'), ('not-done', 'Not Done'), ('on-hold', 'On Hold'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('entered-in-error', 'Entered In Error'), ('unknown', 'Unknown')], max_length=32),
        ),
        migrations.AlterField(
            model_name='nutritionorder',
            name='schedule',
            field=models.JSONField(help_text='FHIR Timing object'),
        ),
        migrations.AlterField(
            model_name='nutritionorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('on-hold', 'On Hold'), ('entered-in-error', 'Entered In Error'), ('ended', 'Ended'), ('completed', 'Completed'), ('revoked', 'Revoked'), ('unknown', 'Unknown')], max_length=32),
        ),
    ]
