# Generated by Django 5.1.4 on 2025-08-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_diet', '0003_nutritionintake_nutrition_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionintake',
            name='nutrition_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_logs', to='care_diet.nutritionorder'),
        ),
    ]
