# Generated by Django 5.1.4 on 2025-08-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_diet', '0004_alter_nutritionintake_nutrition_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionorder',
            name='patient_allergies',
            field=models.JSONField(blank=True, help_text='Point-in-time snapshot of patient allergies when order was created', null=True),
        ),
    ]
