# Generated by Django 5.1.4 on 2025-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_diet', '0005_nutritionorder_patient_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionproduct',
            name='allergens',
            field=models.JSONField(default=list, help_text='List of allergy codes from system-allergy-code valueset. Each item should be a coding object with system, code, and display fields.'),
        ),
    ]
