# Generated by Django 5.1.4 on 2025-08-23 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_diet', '0006_alter_nutritionproduct_allergens'),
        ('emr', '0030_encounter_tags_medicationrequest_dispense_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionintake',
            name='charge_item',
            field=models.ForeignKey(blank=True, help_text='ChargeItem created for billing this nutrition intake', null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.chargeitem'),
        ),
        migrations.AddField(
            model_name='nutritionproduct',
            name='charge_item_definition',
            field=models.ForeignKey(blank=True, help_text='ChargeItemDefinition used for billing when this product is ordered', null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.chargeitemdefinition'),
        ),
    ]
